name: Build and test
on: [push, pull_request, workflow_dispatch]
env:
  GRADLE_CACHE_USERNAME: apikey
  GRADLE_CACHE_PUSH: true
  GRADLE_CACHE_LOCAL: false
  GRADLE_CACHE_REMOTE: true
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Configure JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Setup PostgreSQL
        run: sudo postgres/setup.sh
      - name: Setup MySQL
        run: sudo mysql/setup.sh
      - name: Setup Gradle
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
      - name: Gradle check
        run: ./gradlew check --scan

